// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpnxkyyjhxogcpctidqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwbnhreXlqaHhvZ2NwY3RpZHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NDk0MzcsImV4cCI6MjA4NzAyNTQzN30.NU9zx7X1jRa1mXLlqqP-hCOQBBljjN2O3ES-4qLNxYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
    lock: false,
  }
});
